CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" char(60) NOT NULL,
  "email" varchar UNIQUE,
  "phone_number" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "price" decimal(10,2),
  "category_id" integer,
  "condition" varchar,
  "location" varchar,
  "image_url" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "contact_info" varchar,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

COMMENT ON COLUMN "posts"."description" IS 'Overview of the listing';

COMMENT ON COLUMN "posts"."price" IS 'Price in USD';

COMMENT ON COLUMN "posts"."condition" IS 'New, Like New, Used, etc.';

COMMENT ON COLUMN "posts"."location" IS 'Optional campus area or city';

COMMENT ON COLUMN "posts"."image_url" IS 'URL or path to the post image';

COMMENT ON COLUMN "categories"."name" IS 'Example: Textbooks, Furniture, Electronics';

ALTER TABLE IF EXISTS "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE IF EXISTS "posts" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");



/* Commands Used to Test and Verify the Tables Creation */
-- docker compose up --build
-- docker exec -it project_db psql -U postgres -d marketplace
-- \dt

/*
           List of relations
 Schema |    Name    | Type  |  Owner   
--------+------------+-------+----------
 public | categories | table | postgres
 public | posts      | table | postgres
 public | users      | table | postgres
 */

 -- docker compose down -v